version: '3'
networks:
  imlogic_net:

services:
  imlogic:
    image: mymodd:latest
    container_name: imlogic
    working_dir: /go/imlogic
    networks:
      - imlogic_net
    volumes:
      - .:/go/imlogic
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - imlogic_net
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "14806:8086"
    environment:
      TZ: Asia/Shanghai
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: VBrxAR87kVuC9bxYjDpH
      DOCKER_INFLUXDB_INIT_ORG: imlogic-org
      DOCKER_INFLUXDB_INIT_BUCKET: imlogic-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 1q2w3e4r5t6y7u8i9o0p
    volumes:
      - ~/devenv/docker-env/data/influxdb-data:/var/lib/influxdb/data
    networks:
      - imlogic_net

