version: '3'
networks:
  env_net:
    external: true
  imlogic_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  imlogic:
    image: mymodd:latest
    container_name: imlogic
    working_dir: /go/imlogic
    networks:
      - env_net
      - imlogic_net
    volumes:
      - ~/开发/go/src/imlogic/backend:/go/imlogic
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - imlogic_net
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "18086:8086"
    environment:
      TZ: Asia/Shanghai
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: VBrxAR87kVuC9bxYjDpH
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 1q2w3e4r5t6y7u8i9o0p
    volumes:
      - ~/devenv/docker-env/data/influxdb-data:/var/lib/influxdb/data
    networks:
      - imlogic_net

