// Code generated by ent, DO NOT EDIT.

package groupmessage

import (
	"imlogic/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldID, id))
}

// MsgType applies equality check predicate on the "msg_type" field. It's identical to MsgTypeEQ.
func MsgType(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldMsgType, v))
}

// MsgID applies equality check predicate on the "msg_id" field. It's identical to MsgIDEQ.
func MsgID(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldMsgID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldGroupID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldTimestamp, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldSenderID, v))
}

// MsgTypeEQ applies the EQ predicate on the "msg_type" field.
func MsgTypeEQ(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldMsgType, v))
}

// MsgTypeNEQ applies the NEQ predicate on the "msg_type" field.
func MsgTypeNEQ(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldMsgType, v))
}

// MsgTypeIn applies the In predicate on the "msg_type" field.
func MsgTypeIn(vs ...int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldMsgType, vs...))
}

// MsgTypeNotIn applies the NotIn predicate on the "msg_type" field.
func MsgTypeNotIn(vs ...int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldMsgType, vs...))
}

// MsgTypeGT applies the GT predicate on the "msg_type" field.
func MsgTypeGT(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldMsgType, v))
}

// MsgTypeGTE applies the GTE predicate on the "msg_type" field.
func MsgTypeGTE(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldMsgType, v))
}

// MsgTypeLT applies the LT predicate on the "msg_type" field.
func MsgTypeLT(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldMsgType, v))
}

// MsgTypeLTE applies the LTE predicate on the "msg_type" field.
func MsgTypeLTE(v int32) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldMsgType, v))
}

// MsgIDEQ applies the EQ predicate on the "msg_id" field.
func MsgIDEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldMsgID, v))
}

// MsgIDNEQ applies the NEQ predicate on the "msg_id" field.
func MsgIDNEQ(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldMsgID, v))
}

// MsgIDIn applies the In predicate on the "msg_id" field.
func MsgIDIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldMsgID, vs...))
}

// MsgIDNotIn applies the NotIn predicate on the "msg_id" field.
func MsgIDNotIn(vs ...string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldMsgID, vs...))
}

// MsgIDGT applies the GT predicate on the "msg_id" field.
func MsgIDGT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldMsgID, v))
}

// MsgIDGTE applies the GTE predicate on the "msg_id" field.
func MsgIDGTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldMsgID, v))
}

// MsgIDLT applies the LT predicate on the "msg_id" field.
func MsgIDLT(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldMsgID, v))
}

// MsgIDLTE applies the LTE predicate on the "msg_id" field.
func MsgIDLTE(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldMsgID, v))
}

// MsgIDContains applies the Contains predicate on the "msg_id" field.
func MsgIDContains(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContains(FieldMsgID, v))
}

// MsgIDHasPrefix applies the HasPrefix predicate on the "msg_id" field.
func MsgIDHasPrefix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasPrefix(FieldMsgID, v))
}

// MsgIDHasSuffix applies the HasSuffix predicate on the "msg_id" field.
func MsgIDHasSuffix(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldHasSuffix(FieldMsgID, v))
}

// MsgIDEqualFold applies the EqualFold predicate on the "msg_id" field.
func MsgIDEqualFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEqualFold(FieldMsgID, v))
}

// MsgIDContainsFold applies the ContainsFold predicate on the "msg_id" field.
func MsgIDContainsFold(v string) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldContainsFold(FieldMsgID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldGroupID, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldTimestamp, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v int64) predicate.GroupMessage {
	return predicate.GroupMessage(sql.FieldLTE(FieldSenderID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupMessage) predicate.GroupMessage {
	return predicate.GroupMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupMessage) predicate.GroupMessage {
	return predicate.GroupMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupMessage) predicate.GroupMessage {
	return predicate.GroupMessage(sql.NotPredicates(p))
}
