// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"imlogic/ent/predicate"
	"imlogic/ent/userrole"
)

// UserRoleUpdate is the builder for updating UserRole entities.
type UserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *UserRoleMutation
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (uru *UserRoleUpdate) Where(ps ...predicate.UserRole) *UserRoleUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// SetUpdatedAt sets the "updated_at" field.
func (uru *UserRoleUpdate) SetUpdatedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetUpdatedAt(t)
	return uru
}

// SetDeleted sets the "deleted" field.
func (uru *UserRoleUpdate) SetDeleted(b bool) *UserRoleUpdate {
	uru.mutation.SetDeleted(b)
	return uru
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableDeleted(b *bool) *UserRoleUpdate {
	if b != nil {
		uru.SetDeleted(*b)
	}
	return uru
}

// SetCreator sets the "creator" field.
func (uru *UserRoleUpdate) SetCreator(i int64) *UserRoleUpdate {
	uru.mutation.ResetCreator()
	uru.mutation.SetCreator(i)
	return uru
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableCreator(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetCreator(*i)
	}
	return uru
}

// AddCreator adds i to the "creator" field.
func (uru *UserRoleUpdate) AddCreator(i int64) *UserRoleUpdate {
	uru.mutation.AddCreator(i)
	return uru
}

// SetEditor sets the "editor" field.
func (uru *UserRoleUpdate) SetEditor(i int64) *UserRoleUpdate {
	uru.mutation.ResetEditor()
	uru.mutation.SetEditor(i)
	return uru
}

// SetNillableEditor sets the "editor" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableEditor(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetEditor(*i)
	}
	return uru
}

// AddEditor adds i to the "editor" field.
func (uru *UserRoleUpdate) AddEditor(i int64) *UserRoleUpdate {
	uru.mutation.AddEditor(i)
	return uru
}

// SetVersion sets the "version" field.
func (uru *UserRoleUpdate) SetVersion(i int64) *UserRoleUpdate {
	uru.mutation.ResetVersion()
	uru.mutation.SetVersion(i)
	return uru
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableVersion(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetVersion(*i)
	}
	return uru
}

// AddVersion adds i to the "version" field.
func (uru *UserRoleUpdate) AddVersion(i int64) *UserRoleUpdate {
	uru.mutation.AddVersion(i)
	return uru
}

// SetUserID sets the "user_id" field.
func (uru *UserRoleUpdate) SetUserID(i int64) *UserRoleUpdate {
	uru.mutation.ResetUserID()
	uru.mutation.SetUserID(i)
	return uru
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableUserID(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetUserID(*i)
	}
	return uru
}

// AddUserID adds i to the "user_id" field.
func (uru *UserRoleUpdate) AddUserID(i int64) *UserRoleUpdate {
	uru.mutation.AddUserID(i)
	return uru
}

// SetRoleID sets the "role_id" field.
func (uru *UserRoleUpdate) SetRoleID(i int64) *UserRoleUpdate {
	uru.mutation.ResetRoleID()
	uru.mutation.SetRoleID(i)
	return uru
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableRoleID(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetRoleID(*i)
	}
	return uru
}

// AddRoleID adds i to the "role_id" field.
func (uru *UserRoleUpdate) AddRoleID(i int64) *UserRoleUpdate {
	uru.mutation.AddRoleID(i)
	return uru
}

// Mutation returns the UserRoleMutation object of the builder.
func (uru *UserRoleUpdate) Mutation() *UserRoleMutation {
	return uru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UserRoleUpdate) Save(ctx context.Context) (int, error) {
	uru.defaults()
	return withHooks(ctx, uru.sqlSave, uru.mutation, uru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UserRoleUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UserRoleUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uru *UserRoleUpdate) defaults() {
	if _, ok := uru.mutation.UpdatedAt(); !ok {
		v := userrole.UpdateDefaultUpdatedAt()
		uru.mutation.SetUpdatedAt(v)
	}
}

func (uru *UserRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userrole.Table, userrole.Columns, sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt64))
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uru.mutation.Deleted(); ok {
		_spec.SetField(userrole.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := uru.mutation.Creator(); ok {
		_spec.SetField(userrole.FieldCreator, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedCreator(); ok {
		_spec.AddField(userrole.FieldCreator, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.Editor(); ok {
		_spec.SetField(userrole.FieldEditor, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedEditor(); ok {
		_spec.AddField(userrole.FieldEditor, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.Version(); ok {
		_spec.SetField(userrole.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedVersion(); ok {
		_spec.AddField(userrole.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.UserID(); ok {
		_spec.SetField(userrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedUserID(); ok {
		_spec.AddField(userrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.RoleID(); ok {
		_spec.SetField(userrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedRoleID(); ok {
		_spec.AddField(userrole.FieldRoleID, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uru.mutation.done = true
	return n, nil
}

// UserRoleUpdateOne is the builder for updating a single UserRole entity.
type UserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uruo *UserRoleUpdateOne) SetUpdatedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetUpdatedAt(t)
	return uruo
}

// SetDeleted sets the "deleted" field.
func (uruo *UserRoleUpdateOne) SetDeleted(b bool) *UserRoleUpdateOne {
	uruo.mutation.SetDeleted(b)
	return uruo
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableDeleted(b *bool) *UserRoleUpdateOne {
	if b != nil {
		uruo.SetDeleted(*b)
	}
	return uruo
}

// SetCreator sets the "creator" field.
func (uruo *UserRoleUpdateOne) SetCreator(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetCreator()
	uruo.mutation.SetCreator(i)
	return uruo
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableCreator(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetCreator(*i)
	}
	return uruo
}

// AddCreator adds i to the "creator" field.
func (uruo *UserRoleUpdateOne) AddCreator(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddCreator(i)
	return uruo
}

// SetEditor sets the "editor" field.
func (uruo *UserRoleUpdateOne) SetEditor(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetEditor()
	uruo.mutation.SetEditor(i)
	return uruo
}

// SetNillableEditor sets the "editor" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableEditor(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetEditor(*i)
	}
	return uruo
}

// AddEditor adds i to the "editor" field.
func (uruo *UserRoleUpdateOne) AddEditor(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddEditor(i)
	return uruo
}

// SetVersion sets the "version" field.
func (uruo *UserRoleUpdateOne) SetVersion(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetVersion()
	uruo.mutation.SetVersion(i)
	return uruo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableVersion(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetVersion(*i)
	}
	return uruo
}

// AddVersion adds i to the "version" field.
func (uruo *UserRoleUpdateOne) AddVersion(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddVersion(i)
	return uruo
}

// SetUserID sets the "user_id" field.
func (uruo *UserRoleUpdateOne) SetUserID(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetUserID()
	uruo.mutation.SetUserID(i)
	return uruo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableUserID(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetUserID(*i)
	}
	return uruo
}

// AddUserID adds i to the "user_id" field.
func (uruo *UserRoleUpdateOne) AddUserID(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddUserID(i)
	return uruo
}

// SetRoleID sets the "role_id" field.
func (uruo *UserRoleUpdateOne) SetRoleID(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetRoleID()
	uruo.mutation.SetRoleID(i)
	return uruo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableRoleID(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetRoleID(*i)
	}
	return uruo
}

// AddRoleID adds i to the "role_id" field.
func (uruo *UserRoleUpdateOne) AddRoleID(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddRoleID(i)
	return uruo
}

// Mutation returns the UserRoleMutation object of the builder.
func (uruo *UserRoleUpdateOne) Mutation() *UserRoleMutation {
	return uruo.mutation
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (uruo *UserRoleUpdateOne) Where(ps ...predicate.UserRole) *UserRoleUpdateOne {
	uruo.mutation.Where(ps...)
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UserRoleUpdateOne) Select(field string, fields ...string) *UserRoleUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UserRole entity.
func (uruo *UserRoleUpdateOne) Save(ctx context.Context) (*UserRole, error) {
	uruo.defaults()
	return withHooks(ctx, uruo.sqlSave, uruo.mutation, uruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) SaveX(ctx context.Context) *UserRole {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uruo *UserRoleUpdateOne) defaults() {
	if _, ok := uruo.mutation.UpdatedAt(); !ok {
		v := userrole.UpdateDefaultUpdatedAt()
		uruo.mutation.SetUpdatedAt(v)
	}
}

func (uruo *UserRoleUpdateOne) sqlSave(ctx context.Context) (_node *UserRole, err error) {
	_spec := sqlgraph.NewUpdateSpec(userrole.Table, userrole.Columns, sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt64))
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrole.FieldID)
		for _, f := range fields {
			if !userrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uruo.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uruo.mutation.Deleted(); ok {
		_spec.SetField(userrole.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := uruo.mutation.Creator(); ok {
		_spec.SetField(userrole.FieldCreator, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedCreator(); ok {
		_spec.AddField(userrole.FieldCreator, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.Editor(); ok {
		_spec.SetField(userrole.FieldEditor, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedEditor(); ok {
		_spec.AddField(userrole.FieldEditor, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.Version(); ok {
		_spec.SetField(userrole.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedVersion(); ok {
		_spec.AddField(userrole.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.UserID(); ok {
		_spec.SetField(userrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedUserID(); ok {
		_spec.AddField(userrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.RoleID(); ok {
		_spec.SetField(userrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedRoleID(); ok {
		_spec.AddField(userrole.FieldRoleID, field.TypeInt64, value)
	}
	_node = &UserRole{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uruo.mutation.done = true
	return _node, nil
}
