// Code generated by Kitex v0.7.3. DO NOT EDIT.

package publicsrv

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	public "github.com/xu756/imlogic/kitex_gen/public"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return publicSrvServiceInfo
}

var publicSrvServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "PublicSrv"
	handlerType := (*public.PublicSrv)(nil)
	methods := map[string]kitex.MethodInfo{
		"LoginByPassword": kitex.NewMethodInfo(loginByPasswordHandler, newLoginByPasswordArgs, newLoginByPasswordResult, false),
		"LoginByMobile":   kitex.NewMethodInfo(loginByMobileHandler, newLoginByMobileArgs, newLoginByMobileResult, false),
		"SendCaptcha":     kitex.NewMethodInfo(sendCaptchaHandler, newSendCaptchaArgs, newSendCaptchaResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "public",
		"ServiceFilePath": ``,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.7.3",
		Extra:           extra,
	}
	return svcInfo
}

func loginByPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(public.LoginByPasswordReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(public.PublicSrv).LoginByPassword(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *LoginByPasswordArgs:
		success, err := handler.(public.PublicSrv).LoginByPassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginByPasswordResult)
		realResult.Success = success
	}
	return nil
}
func newLoginByPasswordArgs() interface{} {
	return &LoginByPasswordArgs{}
}

func newLoginByPasswordResult() interface{} {
	return &LoginByPasswordResult{}
}

type LoginByPasswordArgs struct {
	Req *public.LoginByPasswordReq
}

func (p *LoginByPasswordArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(public.LoginByPasswordReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LoginByPasswordArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LoginByPasswordArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LoginByPasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginByPasswordArgs) Unmarshal(in []byte) error {
	msg := new(public.LoginByPasswordReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginByPasswordArgs_Req_DEFAULT *public.LoginByPasswordReq

func (p *LoginByPasswordArgs) GetReq() *public.LoginByPasswordReq {
	if !p.IsSetReq() {
		return LoginByPasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginByPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginByPasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginByPasswordResult struct {
	Success *public.LoginRes
}

var LoginByPasswordResult_Success_DEFAULT *public.LoginRes

func (p *LoginByPasswordResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(public.LoginRes)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LoginByPasswordResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LoginByPasswordResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LoginByPasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginByPasswordResult) Unmarshal(in []byte) error {
	msg := new(public.LoginRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginByPasswordResult) GetSuccess() *public.LoginRes {
	if !p.IsSetSuccess() {
		return LoginByPasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginByPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*public.LoginRes)
}

func (p *LoginByPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginByPasswordResult) GetResult() interface{} {
	return p.Success
}

func loginByMobileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(public.LoginByMobileReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(public.PublicSrv).LoginByMobile(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *LoginByMobileArgs:
		success, err := handler.(public.PublicSrv).LoginByMobile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginByMobileResult)
		realResult.Success = success
	}
	return nil
}
func newLoginByMobileArgs() interface{} {
	return &LoginByMobileArgs{}
}

func newLoginByMobileResult() interface{} {
	return &LoginByMobileResult{}
}

type LoginByMobileArgs struct {
	Req *public.LoginByMobileReq
}

func (p *LoginByMobileArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(public.LoginByMobileReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LoginByMobileArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LoginByMobileArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LoginByMobileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginByMobileArgs) Unmarshal(in []byte) error {
	msg := new(public.LoginByMobileReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginByMobileArgs_Req_DEFAULT *public.LoginByMobileReq

func (p *LoginByMobileArgs) GetReq() *public.LoginByMobileReq {
	if !p.IsSetReq() {
		return LoginByMobileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginByMobileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginByMobileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginByMobileResult struct {
	Success *public.LoginRes
}

var LoginByMobileResult_Success_DEFAULT *public.LoginRes

func (p *LoginByMobileResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(public.LoginRes)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LoginByMobileResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LoginByMobileResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LoginByMobileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginByMobileResult) Unmarshal(in []byte) error {
	msg := new(public.LoginRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginByMobileResult) GetSuccess() *public.LoginRes {
	if !p.IsSetSuccess() {
		return LoginByMobileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginByMobileResult) SetSuccess(x interface{}) {
	p.Success = x.(*public.LoginRes)
}

func (p *LoginByMobileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginByMobileResult) GetResult() interface{} {
	return p.Success
}

func sendCaptchaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(public.SendCaptchaReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(public.PublicSrv).SendCaptcha(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *SendCaptchaArgs:
		success, err := handler.(public.PublicSrv).SendCaptcha(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SendCaptchaResult)
		realResult.Success = success
	}
	return nil
}
func newSendCaptchaArgs() interface{} {
	return &SendCaptchaArgs{}
}

func newSendCaptchaResult() interface{} {
	return &SendCaptchaResult{}
}

type SendCaptchaArgs struct {
	Req *public.SendCaptchaReq
}

func (p *SendCaptchaArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(public.SendCaptchaReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SendCaptchaArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SendCaptchaArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SendCaptchaArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendCaptchaArgs) Unmarshal(in []byte) error {
	msg := new(public.SendCaptchaReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendCaptchaArgs_Req_DEFAULT *public.SendCaptchaReq

func (p *SendCaptchaArgs) GetReq() *public.SendCaptchaReq {
	if !p.IsSetReq() {
		return SendCaptchaArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendCaptchaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendCaptchaArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendCaptchaResult struct {
	Success *public.SendCaptchaRes
}

var SendCaptchaResult_Success_DEFAULT *public.SendCaptchaRes

func (p *SendCaptchaResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(public.SendCaptchaRes)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SendCaptchaResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SendCaptchaResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SendCaptchaResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendCaptchaResult) Unmarshal(in []byte) error {
	msg := new(public.SendCaptchaRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendCaptchaResult) GetSuccess() *public.SendCaptchaRes {
	if !p.IsSetSuccess() {
		return SendCaptchaResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendCaptchaResult) SetSuccess(x interface{}) {
	p.Success = x.(*public.SendCaptchaRes)
}

func (p *SendCaptchaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendCaptchaResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LoginByPassword(ctx context.Context, Req *public.LoginByPasswordReq) (r *public.LoginRes, err error) {
	var _args LoginByPasswordArgs
	_args.Req = Req
	var _result LoginByPasswordResult
	if err = p.c.Call(ctx, "LoginByPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginByMobile(ctx context.Context, Req *public.LoginByMobileReq) (r *public.LoginRes, err error) {
	var _args LoginByMobileArgs
	_args.Req = Req
	var _result LoginByMobileResult
	if err = p.c.Call(ctx, "LoginByMobile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendCaptcha(ctx context.Context, Req *public.SendCaptchaReq) (r *public.SendCaptchaRes, err error) {
	var _args SendCaptchaArgs
	_args.Req = Req
	var _result SendCaptchaResult
	if err = p.c.Call(ctx, "SendCaptcha", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
