Addr:
  ApiAddr: 0.0.0.0:7080
  UserAddr: 0.0.0.0:7081
  ImAddr: 0.0.0.0:7082 # ws 地址
  ImServerAddr: 0.0.0.0:7083 # 调用ws rpc 地址
  ImHandlerAddr: 0.0.0.0:7084 # 处理ws消息的rpc地址

Rpc:
  UserRpc: 0.0.0.0:7081
  ImServerAddr: 0.0.0.0:7083
  ImHandlerAddr: 0.0.0.0:7084

DbConfig:
  DbType: postgres
  Addr: postgresql.db
  Port: 15432
  Username: root
  Password: imlogic
  DbName: imlogic

RedisConfig:
  Addr: 110.40.208.122:16379
  Password: imlogic
  Db: 4
  Prefix: imlogic

UploadPath: ./build/file
CosUrl: https://cos.imlogic.cn/appserver

JwtConfig:
  SignKey: Tqede8rNvZvbKmjqYpQRvwLxsGR
  Expire: 3600000


MqUrl: amqp://root:imlogic@productLinux:5672/
Version: v1

Minio:
  Endpoint: cos.imlogic.cn
  AccessKeyID: dev 
  SecretAccessKey:  
  UseSSL: false 
  Bucket: dev


openTelemetry:
  addr: https://log.imlogic.cn
  endpoint: log.imlogic.cn:15081
  stream: imlogic
  userName: imlogic@qq.com
  passWord: imlogic123
  fullSize: 20

MongodbUrl: mongodb://root:fyU0bj2KLndYN6CKYubb@productLinux:17017
