Addr:
  ApiAddr: 0.0.0.0:7080
  UserAddr: 0.0.0.0:8081
  ImAddr: 0.0.0.0:7082 # ws 地址
  ImServerAddr: 0.0.0.0:7083 # 调用ws rpc 地址
  ImHandlerAddr: 0.0.0.0:7084 # 处理ws消息的rpc地址

Rpc:
  UserRpc: 0.0.0.0:8081
  ImServerAddr: 0.0.0.0:7083
  ImHandlerAddr: 0.0.0.0:7084

DbConfig:
  DbType: postgres
  Addr: 110.40.208.122
  Port: 15432
  Username: root
  Password: fyU0bj2KLndYN6CKYubb
  DbName: imlogic

RedisConfig:
  Addr: 110.40.208.122:16379
  Password: Y5dg5tg8050oigInC30sf
  Db: 4
  Prefix: imlogic

uploadPath: ./build/file
cosUrl: https://cos.imlogic.cn/appserver

JwtConfig:
  SignKey: Tqede8rNvZvbKmjqYpQRvwLxsGR
  Expire: 3600000


MqUrl: amqp://root:1mYa0PE6JLz8U5YJYMgj@192.168.0.105:5672/
Version: v1
Minio:
  Endpoint: cos.imlogic.cn
  AccessKeyID: nJQ8MGtvnWfgHJXu0pFS 
  SecretAccessKey:  
  UseSSL: false 
  Bucket: appserver

MongodbUrl: mongodb://root:fyU0bj2KLndYN6CKYubb@110.40.208.122:17017