Addr:
  ApiAddr: "0.0.0.0:7080"
  UserAddr: "0.0.0.0:8081"
  ImAddr: "0.0.0.0:7082" # ws 地址
  ImServerAddr: "0.0.0.0:7083" # 调用ws rpc 地址
  ImRpcAddr: "0.0.0.0:7084" # 处理ws消息的rpc地址

Rpc:
  UserRpc: "0.0.0.0:8081"
  ImServerAddr: "0.0.0.0:7083"
  ImRpcAddr: "0.0.0.0:7084"

DbConfig:
  DbType: "postgres"
  Addr: "0.0.0.0"
  Port: 5432
  Username: "root"
  Password: "fyU0bj2KLndYN6CKYubb"
  DbName: "imlogic"

RedisConfig:
  Addr: "0.0.0.0:6379"
  Password: "Y5dg5tg8050oigInC30sf"
  Db: 4
  Prefix: "imlogic"

JwtConfig:
  SignKey: "Tqede8rNvZvbKmjqYpQRvwLxsGR"
  Expire: 3600

EmailConfig:
  SMTPAddr: "smtp.feishu.cn:587"
  Password: "smcfUO20MyiAEijy"
  From: "grade@xynu.email"
  Host: "smtp.feishu.cn"
MqUrl: "amqp://root:PTXzAMnVe7bdYj@localhost:5672/"
Version: "v1"
MinioConfig:
  Endpoint: "" # 需要您提供具体值
  AccessKeyID: "" # 需要您提供具体值
  SecretAccessKey: "" # 需要您提供具体值
  UseSSL: false # 假设为 false，需要您根据实际情况调整
  BucketName: "" # 需要您提供具体值
