[Addr]
ApiAddr = "0.0.0.0:7080"
PublicAddr = "0.0.0.0:8081"
ImAddr = "0.0.0.0:7082"

# 服务发现
[Rpc]
PublicRpc = "0.0.0.0:8081"

[DbConfig]
DbType = "postgres"
Addr = "dataLinux"
Port = 15432
Username = "root"
Password = "fyU0bj2KLndYN6CKYubb"
DbName = "imlogic"

[RedisConfig]
Addr = "dataLinux:16379"
Password = "Y5dg5tg8050oigInC30sf"
Db = 2

[JwtConfig]
SignKey = "Tqede8rNvZvbKmjqYpQRvwLxsGR"
Expire = 3600


[EmailConfig]
SMTPAddr = "smtp.feishu.cn:587"
Password = "smcfUO20MyiAEijy"
From = "grade@xynu.email"
Host = "smtp.feishu.cn"



[Etcd]
Addrs = ["47.96.152.242:12379"]