[Addr]
# 服务地址 运行地址
ApiAddr = "0.0.0.0:7080"
PublicAddr = "0.0.0.0:8081"
ImAddr = "0.0.0.0:7082" #  ws 地址
ImServerAddr = "0.0.0.0:7083" #调用ws rpc 地址
ImRpcAddr = "0.0.0.0:7084"  # 处理ws消息的rpc地址

# 服务发现 调用的地址
[Rpc]
PublicRpc = "0.0.0.0:8081"
ImServerAddr = "0.0.0.0:7083"
ImRpcAddr = "0.0.0.0:7084"


[DbConfig]
DbType = "postgres"
Addr = "127.0.0.1"
Port = 15432
Username = "root"
Password = "fyU0bj2KLndYN6CKYubb"
DbName = "imlogic"

[RedisConfig]
Addr = "127.0.0.1:16379"
Password = "Y5dg5tg8050oigInC30sf"
Db = 2

[JwtConfig]
SignKey = "Tqede8rNvZvbKmjqYpQRvwLxsGR"
Expire = 3600


[EmailConfig]
SMTPAddr = "smtp.feishu.cn:587"
Password = "smcfUO20MyiAEijy"
From = "grade@xynu.email"
Host = "smtp.feishu.cn"



[Etcd]
Addrs = ["47.96.152.242:12379"]